### ISSUE TITLE
SONOS Web App Favorites

### ISSUE THREAD

**Issue by Alex451FH** [ariksidney/sonos-web#5]
I am testing out your SONOS web app and it looks like it works to stop and start our music but the favorites tab is just blank. Am I missing a configuration that needs to be done?

**Comment by ariksidney** [comment]
There's no configuration which needs to be done. Can you check if you get any errors in the dev console and/or in the network requests?

And keep in mind, you only see favourites from Sonos (so the stuff you favourited in the Sonos app) and not your favourites from other services like Spotify, Apple Music and so on.

**Comment by Alex451FH** [comment]
I have deffinitly added Sonos stations to my favorites and the page is still displaying nothing. The sidebar is not even showing when I select Favorites. I have to click back to get back to the Overview page.

**Comment by ariksidney** [comment]
So you only have Sonos Radio stations in your favourites? Or other types (like albums, songs, podcasts, etc) from other sources?

**Comment by ariksidney** [comment]
I just checked the API and it looks like Sonos Radio Stations are indeed not included. 
You can, however, add the stations in your favourites to your Stations and then they show up. Just long press on the station in your favourites and then click "Add Station to My Sonos".

Can you test if that works for you?

**Comment by ariksidney** [comment]
Closing, as API does not allow changes and haven't heard back.
